# примеры API-запросов

@baseUrl = http://localhost:8000/

# получение колицества ингредиентов для омлета
GET {{baseUrl}}/omlet/?servings=80

###

# получение колицества ингредиентов для пасты
GET {{baseUrl}}/pasta/?servings=150

###

# получение колицества ингредиентов для пасты 1 порция
GET {{baseUrl}}/pasta/
